// All measurements come from the three printed reports. Edit this file to change
// numbers, labels or add a new test — the 3D model and every panel are data-driven.
// Use `null` for anything a report did not measure; the UI shows "not measured".

export const SUBJECT = {
  name: 'Mohammad Ali',
  nameFa: 'محمدعلی',
  heightCm: 183,
  sex: 'Male',
};

// Order matters: index 0 = left arm, 1 = right arm, 2 = trunk, 3 = left leg, 4 = right leg
// (display names live in i18n.js)
export const SEGMENTS = [{ id: 'la' }, { id: 'ra' }, { id: 'tr' }, { id: 'll' }, { id: 'rl' }];

export const TESTS = [
  {
    id: 't1',
    short: 'Test 1',
    dateLabel: 'Aug 2025',
    dateNote: 'Printed 9.8.2025',
    fa: { short: 'تست ۱', dateLabel: 'مرداد ۱۴۰۴', dateNote: 'چاپ ۱۸ مرداد ۱۴۰۴' },
    device: 'InBody',
    age: 28,
    weight: 118.0,
    smm: 43.1,
    bfm: 42.8,
    ffm: 75.2,
    softLean: null,
    tbw: 54.8,
    icw: null,
    ecw: null,
    ecwTbw: null,
    protein: 14.9,
    minerals: 5.46,
    pbf: 36.3,
    bmi: 35.2,
    bmr: 1995,
    whr: 0.98,
    vfl: null,
    vfa: null,
    vfaEstimated: false,
    score: 63,
    scoreName: 'Fitness score',
    segments: {
      la: { lean: 4.2, fat: 3.7 },
      ra: { lean: 4.1, fat: 3.8 },
      tr: { lean: 32.0, fat: 21.2 },
      ll: { lean: 12.2, fat: 6.2 },
      rl: { lean: 12.3, fat: 6.3 },
    },
  },
  {
    id: 't2',
    short: 'Test 2',
    dateLabel: 'Date unknown',
    dateNote: 'Device clock printed 2010.01.01',
    fa: { short: 'تست ۲', dateLabel: 'تاریخ نامشخص', dateNote: 'ساعت دستگاه ۲۰۱۰٫۰۱٫۰۱ چاپ کرده' },
    device: 'InBody',
    age: 28,
    weight: 113.8,
    smm: 42.6,
    bfm: 39.3,
    ffm: 74.5,
    softLean: null,
    tbw: 54.3,
    icw: null,
    ecw: null,
    ecwTbw: null,
    protein: 14.8,
    minerals: 5.4,
    pbf: 34.5,
    bmi: 34.0,
    bmr: 1979,
    whr: 1.0,
    vfl: 17,
    vfa: 170, // estimated from level 17 (level x 10 cm²) — the report prints no area
    vfaEstimated: true,
    score: 66,
    scoreName: 'InBody score',
    segments: {
      la: { lean: 4.32, fat: 3.2 },
      ra: { lean: 4.1, fat: 3.4 },
      tr: { lean: 32.1, fat: 20.2 },
      ll: { lean: 11.88, fat: 5.4 },
      rl: { lean: 11.88, fat: 5.5 },
    },
  },
  {
    id: 't3',
    short: 'Test 3',
    dateLabel: '3 Oct 2026',
    dateNote: 'Today',
    fa: { short: 'تست ۳', dateLabel: '۱۱ مهر ۱۴۰۵', dateNote: 'امروز' },
    device: 'Anea BIA 1204',
    age: 29,
    weight: 105.6,
    smm: 40.4,
    bfm: 34.1,
    ffm: 71.4,
    softLean: 66.8,
    tbw: 52.3,
    icw: 32.6,
    ecw: 19.6,
    ecwTbw: 0.37,
    protein: 14.1,
    minerals: 4.9,
    pbf: 32.3,
    bmi: 31.5,
    bmr: 1910.7,
    whr: null,
    vfl: 15,
    vfa: 153.4,
    vfaEstimated: false,
    score: 76,
    scoreName: 'Anea score',
    segments: {
      la: { lean: 4.1, fat: 2.6 },
      ra: { lean: 4.0, fat: 2.6 },
      tr: { lean: 31.6, fat: 18.1 },
      ll: { lean: 11.3, fat: 4.5 },
      rl: { lean: 11.3, fat: 4.6 },
    },
  },
];

// Metric cards. `good` is the direction that is favourable for this person.
// Labels live in i18n.js under `metrics`.
export const METRICS = [
  { key: 'weight', unit: 'kg', dec: 1, good: 'down' },
  { key: 'bfm', unit: 'kg', dec: 1, good: 'down' },
  { key: 'pbf', unit: '%', dec: 1, good: 'down', range: [10, 20] },
  { key: 'smm', unit: 'kg', dec: 1, good: 'up' },
  { key: 'bmi', unit: 'kg/m²', dec: 1, good: 'down', range: [18.5, 25] },
  { key: 'bmr', unit: 'kcal', dec: 0, good: null },
  { key: 'vfa', unit: 'cm²', dec: 0, good: 'down', range: [0, 100] },
  { key: 'tbw', unit: 'L', dec: 1, good: null },
  { key: 'ecwTbw', unit: '', dec: 2, good: null, range: [0.36, 0.39] },
  { key: 'score', unit: '/100', dec: 0, good: 'up' },
];
